// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_ld2pY_8yE1kVb9muQiLyYM6iHiwt2g',
    appId: '1:880725941233:web:8bdbd9c669d3c2fcdc4250',
    messagingSenderId: '880725941233',
    projectId: 'smart-health-96287',
    authDomain: 'smart-health-96287.firebaseapp.com',
    storageBucket: 'smart-health-96287.appspot.com',
    measurementId: 'G-FCHQQ7EG11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYqZvG7GGxx6OOr_ZmpsxrsFCyoRE32Y',
    appId: '1:880725941233:android:69dd16d26a71fe8bdc4250',
    messagingSenderId: '880725941233',
    projectId: 'smart-health-96287',
    storageBucket: 'smart-health-96287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSvcvd4MOSVIc7fVIhbQZAggU71d_m2E',
    appId: '1:880725941233:ios:b8ece06484156883dc4250',
    messagingSenderId: '880725941233',
    projectId: 'smart-health-96287',
    storageBucket: 'smart-health-96287.appspot.com',
    iosBundleId: 'com.example.smartHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMSvcvd4MOSVIc7fVIhbQZAggU71d_m2E',
    appId: '1:880725941233:ios:b8ece06484156883dc4250',
    messagingSenderId: '880725941233',
    projectId: 'smart-health-96287',
    storageBucket: 'smart-health-96287.appspot.com',
    iosBundleId: 'com.example.smartHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_ld2pY_8yE1kVb9muQiLyYM6iHiwt2g',
    appId: '1:880725941233:web:1e99a899793db3e0dc4250',
    messagingSenderId: '880725941233',
    projectId: 'smart-health-96287',
    authDomain: 'smart-health-96287.firebaseapp.com',
    storageBucket: 'smart-health-96287.appspot.com',
    measurementId: 'G-D60DGVH1H0',
  );
}
